### ISSUE TITLE
AttributeError: 'FigureCanvasPdf' object has no attribute 'get_renderer'

### ISSUE THREAD

**Issue by rungitta** [NBISweden/IgDiscover#80] opened 2018-01-16 09:34 UTC
I'm getting this error when I'm running the test on:
https://igdiscover.readthedocs.io/en/latest/testing.html#test

I've just installed it according to the instructions on the same site.  Do you have any idea what might be wrong?

The log and the error message are attached.
[full_error_message.txt](https://github.com/NBISweden/IgDiscover/files/1634386/full_error_message.txt)
 
[2018-01-16T102026.496920.snakemake.log](https://github.com/NBISweden/IgDiscover/files/1634381/2018-01-16T102026.496920.snakemake.log)

**Comment by marcelm** [comment] 2018-01-16 09:42
Thanks for the report. It may be that the plotting library was updated in an incompatible way. I’ll test it and let you know what to do.

**Comment by rungitta** [comment] 2018-01-16 09:47
Thanks a lot!

I just commented out line 700 and line 315 in 
.local/lib/python3.5/site-packages/seaborn/matrix.py
They both had this line of code:
#ax.figure.draw(ax.figure.canvas.get_renderer())

And got actually got through the test:
1 of 2 steps (50%) done

Job 0: IgDiscover finished.

Finished job 0.
2 of 2 steps (100%) done

But I'm not sure what this line actually does. Do I need it? 

-- 
Med vänliga hälsningar,
Axel Rosén

**Comment by marcelm** [comment] 2018-01-16 09:56
This code is from the seaborn package, not directly part of IgDiscover. I saw now that I tried to fix the problem already by requiring the older seaborn 0.7.1 instead of the recent 0.8, see #77, #78 and commit ab458e6aa.

Can you please check which seaborn version you have installed by running `conda list seaborn`?

**Comment by rungitta** [comment] 2018-01-16 10:09
I don't use conda but I downgraded my version of seaborn from 0.8.1 to 0.7.1 
and this in deed solved the problem. 

Bear in mind that when you install igdisover with pip3 then seaborn 0.8.1 is 
installed as a dependency. So you might want to change that.

Thanks a lot :)

-- 
Med vänliga hälsningar,
Axel Rosén

**Comment by marcelm** [comment] 2018-01-16 10:14
Ok, I was assuming you used conda - it is a lot easier and easier to support for us. The pip install way is not as thoroughly tested.

The fix to depend on 0.7.1 and not on any seaborn version is actually already in master, but the package that is on PyPI doesn’t have the fix, yet.

Closing this now as the problem is already fixed. I’m aware we should make a new release, though.

**Closed by marcelm** 2018-01-16 10:14 UTC
